language: c

arch:
  - amd64
  - arm64
  - ppc64le
  - s390x

os:
  - linux
  - osx
  - windows

compiler:
  - gcc
  - clang

dist: trusty

sudo: false

allow_failures:
 - arch: s390x

script:
  - $CC -o hello hello.c
  - ./hello
